[functions.create-user]
verify_jwt = false

[functions.resend-invite]
verify_jwt = false

[functions.bot-telegram]
verify_jwt = false

[functions.send-whatsapp]
[functions.send-message-email]
verify_jwt = false
